{
 "title": "Overview",
 "description": "Mara X Temperatures",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Heat Exchanger",
   "type": "gauge",
   "description": "Latest temperature from the heat exchanger",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "select": [
      [
       { "params": [ "exchangerTempActual" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Steam - Real",
   "type": "gauge",
   "description": "Latest temperature from the Steam Temprature",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "select": [
      [
       { "params": [ "steamTempActual" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Steam -  Target",
   "type": "gauge",
   "description": "Latest temperature from the Steam Temprature",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "select": [
      [
       { "params": [ "steamTempTarget" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heat On / Off / Standby",
   "type": "stat",
   "description": "State of heating element in the steam boiler, it can be on, off or standby",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Thermal coil",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT floor(((mode(\"heatOn\") + 1) * median(\"steamTempTarget\")) / 100) FROM \"tail\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "heatOn" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mode",
   "type": "stat",
   "description": "State of heating element in the steam boiler, it can be on, off or standby",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Thermal coil",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT mode(\"heatOn\") FROM \"tail\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "mode-version" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "State of heating element in the steam boiler, it can be on, off or standby",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Thermal coil",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT mode(\"heatOn\") FROM \"tail\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "mode-version" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heat Exhanger - Real Temprature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "alias": "Brew °C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "select": [
      [
       { "params": [ "exchangerTempActual" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "description": "Target and actual temperatures from steam boiler probe",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "alias": "Steam °C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "select": [
      [
       { "params": [ "steamTempActual" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Target °C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "select": [
      [
       { "params": [ "steamTempTarget" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Brew °C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "select": [
      [
       { "params": [ "exchangerTempActual" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Steam Actual",
   "type": "graph",
   "description": "Target and actual temperatures from steam boiler probe",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "alias": "Steam °C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "select": [
      [
       { "params": [ "steamTempActual" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Steam Target",
   "type": "graph",
   "description": "Target and actual temperatures from steam boiler probe",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "alias": "Target °C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "select": [
      [
       { "params": [ "steamTempTarget" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}