#!/bin/sh

# Sample LINE
# C1.19,085,000,068,0000,0
#new mara X code:

#Switch 1: Xmode steam: C123B,085,000,068,0000,0 
#or
#Switch 0: Xmode coffee: V123B,085,000,068,0000,0 

while read LINE; do
  #if echo "$LINE" | grep -Eq "C\d{1}\.\d{2},\d{3},\d{3},\d{3},\d{4},\d{1}"; then
  if echo "$LINE" | grep -Eq "[A-Za-z0-9]*,\d{3},\d{3},\d{3},\d{4},\d{1}"; then
    echo "$(date +%s),$LINE";
  else
    echo "Regex failed for line [$LINE]" >&2
  fi
done
